# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduleemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100, verbose_name='Día')),
                ('entryTime', models.TimeField(verbose_name='Hora de ingreso')),
                ('departureTime', models.TimeField(verbose_name='Hora de ingreso')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee', verbose_name='Empleado')),
            ],
        ),
    ]
