# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_scheduleemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleemployee',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Cargo'),
        ),
    ]
