# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20160714_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleemployee',
            name='departureTime',
            field=models.TimeField(verbose_name='Hora de salida'),
        ),
    ]
