# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20161016_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=12, null=True, verbose_name='Código'),
        ),
    ]
