# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.Position', verbose_name='Cargo'),
        ),
    ]
