# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20161105_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleemployee',
            name='departureTime',
            field=models.TimeField(null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='scheduleemployee',
            name='entryTime',
            field=models.TimeField(null=True, verbose_name='Hora de ingreso'),
        ),
    ]
