# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_auto_20161121_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Fecha de asistencia')),
                ('dayNumber', models.IntegerField(verbose_name='Número de día')),
                ('day', models.CharField(max_length=100, verbose_name='Día')),
                ('attended', models.BooleanField(default=False, verbose_name='¿Asistió?')),
                ('checkInTime', models.TimeField(null=True, verbose_name='Hora de entrada')),
                ('departureTime', models.TimeField(null=True, verbose_name='Hora de salida')),
                ('delay', models.BooleanField(default=False, verbose_name='¿Tardanza?')),
                ('minutesLate', models.IntegerField(null=True, verbose_name='Minutos de retraso')),
                ('registrationDate', models.DateTimeField(null=True, verbose_name='Fecha y hora de registro')),
                ('modifitacionDate', models.DateTimeField(null=True, verbose_name='Fecha y hora de modificación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee', verbose_name='Id de Empleado')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
