# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('nameposition', models.CharField(max_length=255, verbose_name='Cargo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción de Cargo')),
                ('state', models.CharField(choices=[('ENA', 'Activo'), ('DIS', 'Inactivo')], max_length=3, verbose_name='Estado')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Contrato')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
