# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='modificationdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha y hora de modificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='registrationdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha y hora de registro'),
            preserve_default=False,
        ),
    ]
