# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecontract', models.CharField(max_length=255, verbose_name='Contrato')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción de Contrato')),
                ('state', models.CharField(choices=[('ENA', 'Activo'), ('DIS', 'Inactivo')], max_length=3, verbose_name='Estado')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
